export const R_POINT_GETDATA = 'R_POINT_GETDATA'
export const SHOW_LOADING_RPOINT = 'SHOW_LOADING_RPOINT'
export const R_POINT_GETDATA_FAIL = 'R_POINT_GETDATA_FAIL'

export const NOTICE_GETDATA = 'NOTICE_GETDATA'
export const NOTICE_GETDATA_FAIL = 'NOTICE_GETDATA_FAIL'
export const SHOW_LOADING_NOTICE = 'SHOW_LOADING_NOTICE'

export const PROFILE_GETDATA = 'PROFILE_GETDATA'
export const PROFILE_GETDATA_FAIL = 'PROFILE_GETDATA_FAIL'
export const SHOW_LOADING_PROFILE = 'SHOW_LOADING_PROFILE'
